Create gophermarker
ksusonic/gophermart pull request #1
Opened 2023-03-04 11:03 UTC by ksusonic

2023-03-06 16:04 UTC, Barugoo commented on internal/models/order.go
> +
```go
type OrderStatus string

const (
    OrderStatusNew OrderStatus = "NEW"
)

2023-03-06 16:48 UTC, Barugoo commented on internal/auth/auth.go
> +		ctx.Set("user_id", claims.UserID)
```go
package ctxdata

type ctxKey string

const (
    ctxKeyUserID ctxKey = "user_id"
)

func GetUserID(ctx context.Context) (string, bool) {
     return ctx.Value(ctxKeyUserID).(string)
}

func SetUserID(ctx context.Context, userID string) context.Context {
     return context.WithValue(ctx, ctxKeyUserID, userID)
}

2023-03-17 17:37 UTC, Barugoo commented on cmd/gophermart/main.go
> +		panic(err)
Давай пояснение здесь допишем, что вернуло нам эту ошибку. Для этого лучше подойдет `log.Fatal` (вызов `panic` в `main` в общем-то почти и есть `os.Exit`)
```go
if err != nil {
    log.Fatalf("unable to init config: %v", err)
}

2023-03-17 17:39 UTC, Barugoo commented on internal/accrual/client.go
> +			return err
Тут давай тоже обернем ошибку

2023-03-17 17:43 UTC, Barugoo commented on internal/controller/base.go
> +	CalculateUserStats(userID uint) (userInfo struct{ Balance, Withdraw int64 }, err error)
Давай сделаем структуру `userInfo` именованной и положим куда-нибудь в `models`). Иначе нам в тестах придется обьявлять анонимную структуру с таким же набором полей, прежде чем заполнить ее ожидаемым значением

2023-03-17 17:51 UTC, Barugoo commented on internal/controller/base.go
> +	GetUserWithdraws(userID uint, withdrawals *[]models.Order) error
Нам незачем делать С-style сигнатуры функций (вроде как в Си так принято делать, когда мы хотим сэкономить аллокации переиспользовав уже выделенную память, или когда хотим вернуть больше одного значения из фунукции). Еслу у нас нет острой необходимости переиспользовать уже аллоцированный кусок памяти, то смысла делать такую апи не вижу. 

Давай лучше будем просто возвращать ответ из функции как обычно мы это делаем:
```go
func (d *DB) GetWithdrawnOrdersByUserID(userID uint) (res []models.Order, err error) {
 	return d.Orm.Model(&models.Order{}).Where("user_id = ? and withdraw is not null", userID).Find(&res).Error
 }
``` 

Также рекомендую переименовать функцию `GetUserWithdraws` -> `GetWithdrawnOrdersByUserID`

2023-03-17 17:57 UTC, Barugoo commented on internal/controller/controller.go
> +	if rowsAffected == 0 {
В `database/sql` есть стандартная ошибка для пустого ответа из БД: `sql.ErrNoRows`, ее же будут выкидывать драйвера если условный SELECT вернул ноль записей. 
Эту ошибку по хорошему надо оборачивать в твою собственную ошибку `ErrNotFound`, которую ты обьявишь на слое хранилки и будешь ее пробрасывать наверх (иначе у нас потечет абстракция)

Тогда здесь ты будешь делать 
```go
if errors.Is(err, database.ErrNotFound) {
//...

2023-03-17 17:58 UTC, Barugoo commented on internal/controller/controller.go
> +	if rowsAffected == 0 {
Ну и да, абстракция слегка течет на самом деле уже сейчас, так как `rowsAffected` это понятие применимое, обычно, только к реляционным БД

2023-03-17 18:01 UTC, Barugoo commented on internal/controller/controller.go
> +		logger.Errorf("error retrieving %s: %v", modelName, err)
Так не обязательно же `retrieving` (получение), судя по коду мы этой функцией оборачиваем вообще все ошибки БД, в том числе от методов на вставку
 Лучше сделай название функции более общим (потому что ее содержимое никак не отражает то что ошибка именно из БД), аля `renderIfEntityError` (что она связывает ошибку с сущностьью в коде), а из сообщения убери `retrieving`

Я если что не придираюсь, логгирование суперважно и при первой аварии обычно становится понятно почему

2023-03-17 18:11 UTC, Barugoo commented on internal/controller/controller.go
> +func renderIfDBError(ctx *gin.Context, err error, modelName string, logger *zap.SugaredLogger) bool {
Вообще, кажется, что необходимость прописывать `modelName` руками для каждого вызова этой функции неудобно и приведет к ошибкам по невнимательности

Почему бы просто не заворачивать в ошибку имя сущности непосредственно в том методе, который с ней работает? Тогда нам не придется дублировать вызывающий код и проверять его на соответствие передаваемого `modelName` методу который дергается

```go
func (d *DB) CreateOrder(order *models.Order) (err error) {
        defer func() {
              // когда выполнение дойдет до `defer` в `err` у нас будет лежать значение из вызова `return` 
              // так можно делать, если сделать возвращаемое значение именованым
              return fmt.Errorf("error creating 'order': %w", err) 
        }
 	return d.Orm.Create(order).Error
 }

2023-03-17 18:13 UTC, Barugoo commented on internal/database/db.go
> +		logger.Fatalf("could not migrate User: %v", err)
Давай не фаталить здесь, а прокидывать ошибку наверх, чтобы уже `main` сам принял решение что с ней делать (фаталить)

2023-03-17 18:14 UTC, Barugoo commented on internal/server/server.go
> +		Addr:    ":8080",
Кажется, здесь должен быть `Addr: address`?

2023-03-17 18:16 UTC, Barugoo commented on internal/auth/auth.go
> +func (c *Controller) IsAuthorized() gin.HandlerFunc {
Немного вводит в заблуждение то, что из названия мидлвари у нас есть некая бинарная логика внутри `ок/неок`, а в действительности внутри ты помимо валидации еще подкладываешь `userID` в контекст

Лучше назови `AuthMiddleware`

2023-03-17 18:18 UTC, Barugoo commented on internal/controller/controller.go
> +	expiresAt := time.Now().Add(120 * time.Minute)
Давай вынесем `120 * time.Minute` из функции в именованную константу:
```go
defaultTokenTTL = 120 * time.Minute

2023-03-17 18:19 UTC, Barugoo commented on internal/controller/controller.go
> +	}
Тут тоже правильнее было бы использовать `errors.Is(err, database.ErrNotFound)` (которую ты сам обьявишь и сам же будешь в нее оборачивать ответ из БД `sql.ErrNoRows`)

2023-03-17 18:23 UTC, Barugoo requested changes
В целом отлично, но есть замечания по работе с ошибками и интерфейсу хранилки

2023-03-22 21:51 UTC, ksusonic commented on internal/controller/controller.go
> +func renderIfDBError(ctx *gin.Context, err error, modelName string, logger *zap.SugaredLogger) bool {
тут не получилось сделать с моим случаем

2023-03-23 21:42 UTC, Barugoo commented on internal/controller/controller.go
> +	expiresAt := time.Now().Add(120 * time.Minute)
Ты сделал константу именованую, но не подставил ее сюда

2023-03-23 21:42 UTC, Barugoo approved these changes
Отлично!

2023-03-24 09:08 UTC, merged